---
plugin: amazon.aws.aws_ec2
regions:
  - eu-west-2
  - us-east-2
filters:
  instance-state-name: running
hostnames:
  - instance-id
  # - network-interface.addresses.private-ip-address
keyed_groups:
  - key: tags['ansible_group']
    prefix: tag
    